version: "3.8"
services:
  quarkus-services:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db-quarkus:5432/jobadvertisement
    ports:
      - "8080:8080"
    depends_on:
      - "db-quarkus"
    networks:
      - quarkus

  db-quarkus:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres_user
      - POSTRGRES_PASSWORD=postgres_password
      - POSTGRES_DB=jobadvertisement
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge

